### ISSUE TITLE
能否提供一个动态改变日志级别的例子

### ISSUE THREAD

**Issue by KevinHe666** [alipay/sofa-common-tools#19]
@guanchao-yang 您好,框架动态日志级别修改的测试类可以提供一个 在方法级可动态改变此日志的级别

**Comment by guanchao-yang** [comment]
@KevinHe666 `com.alipay.sofa.common.log.MultiAppLoggerSpaceManager#setLoggerLevel(java.lang.String, com.alipay.sofa.common.log.SpaceId, com.alipay.sofa.common.log.adapter.level.AdapterLevel)` 封装的接口这个就是哈，比其他接口，多了一个 `com.alipay.sofa.common.log.adapter.level.AdapterLevel` 的传入。

**Comment by KevinHe666** [comment]
@guanchao-yang 您好 还有个问题我本机测试 System.setProperty(Constants.LOGBACK_MIDDLEWARE_LOG_DISABLE_PROP_KEY, "true");设置这个之后是不走logback 走log4j2的日志,但是注释掉上面那句话之后 logback无法打印日志了 这是否是我哪儿里疏忽了么?正常不应该注释掉就可以走logback日志了么现在测试无法打印logback

**Comment by KevinHe666** [comment]
@guanchao-yang 上面的已经解决了 不好意思
