### ISSUE TITLE
Provide a mechanism for guaranteeing error log output in console

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-common-tools#20]
When application started in IDE,error occurs during bootstrap and the error log output like `common-error.log` .When the commponents are too more ,the error output to file not easy to find。So, providing a mechanism for guaranteeing error log output in console when run in IDE  for better experience

**Comment by leizhiyuan** [comment]
commons-tools can read key in System.properties("print_to_console")

if true, common-tools will print all logs to files and consoles.
if false or null,common-tools will print all logs to files

**Comment by QilongZhang** [comment]
@leizhiyuan  is it too many to print all logs to console?
