### ISSUE TITLE
String Index out of range 问题

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-common-tools#42]
### Describe the bug
com.alipay.sofa.common.boot.logging.CommonLoggingApplicationListener#reInitializeLog 方法中,入参 map 的一个 key 为`sofa.middleware.log.disable`,运行到第74行时,实际上是:
```
 int index = Constants.SOFA_MIDDLEWARE_CONFIG_PREFIX.length();//20
int end = "sofa.middleware.log.disable".length() - 9;//19
key.substring(20, 19)
```

然后就报错了

### Environment

- sofa-common-tools version: 1.0.16
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
感谢反馈，没有考虑到 `sofa.middleware.log.disable` 这个配置，我们会在下个版本修复。 

另外参考[日志配置声明](https://github.com/alipay/sofa-common-tools#%E5%9B%9B%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E) ， `sofa.middleware.log.disable` 只能通过 `-D` 参数传入，禁止所有日志打印不是推荐做法，最新版本提供了更灵活的日志配置，如果为了打印较少日志，你可以使用通配符设置提高日志打印级别，例如 `logging.level.com.* = warn`
